[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
lines_after_imports = 2
use_parentheses = true
ensure_newline_before_comments = true
known_third_party = ["django", "rest_framework", "setuptools"]
known_first_party = ["about", "api", "core", "posts", "recipes", "reviews", "users"]
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]